"""Pin that the TWAP side schedule does not alias with the training schedule.

An independent review found that in a 1-on/0-off ALTERNATING run
(`TWAP_ON=1, TWAP_OFF=0, TWAP_SIDE_MODE=alternate`, i.e. `both_base`) the side
has period 2 while training fires on `episode % 4 == 0`. Because 2 divides 4,
side and training phase are locked: every training session lands on a buy
episode, and buy and sell episodes are systematically generated by policies of
different age. Pairing adjacent episodes does NOT fix it -- the buy member of
every pair is always the just-updated one.

The 2-on/1-off alternating schedule this project now uses gives the side period
3, which is coprime with the training period 4 and the CEM period 8, so the
phases cycle and average out. These tests pin that property, because it is the
difference between a criterion-1 contrast that means something and one that is
confounded with training phase.
"""
import sys
from math import gcd

TRAIN_PERIOD = 4     # AR_RL_Trainer: `if ((episode) % 4 == 0)`
CEM_PERIOD = 8       # `use_CEM = bool(episode % 8)`


def schedule(n, on, off, mode="alternate"):
    """Reproduce the trainer's presence/side logic exactly."""
    out, n_present = [], 0
    for e in range(n):
        present = (e % (on + off)) < on
        if mode == "alternate":
            side = "buy" if (n_present % 2 == 0) else "sell"
        else:
            side = mode
        if present:
            n_present += 1
        out.append((e, present, side if present else "none"))
    return out


def side_period(on, off, n=240):
    s = schedule(n, on, off)
    labels = [x[2] for x in s]
    for p in range(1, 40):
        if all(labels[i] == labels[i % p] for i in range(len(labels))):
            return p
    return None


def test_two_on_one_off_has_side_period_three():
    assert side_period(2, 1) == 3
    s = schedule(9, 2, 1)
    assert [x[2] for x in s] == ["buy", "sell", "none"] * 3, s


def test_one_on_zero_off_has_side_period_two():
    """The schedule the review flagged as confounded."""
    assert side_period(1, 0) == 2


def test_the_live_schedule_is_coprime_with_training_and_cem():
    """This is the property that makes the criterion-1 contrast interpretable."""
    p = side_period(2, 1)
    assert gcd(p, TRAIN_PERIOD) == 1, (p, TRAIN_PERIOD)
    assert gcd(p, CEM_PERIOD) == 1, (p, CEM_PERIOD)


def test_the_flagged_schedule_is_not_coprime():
    """Pin the failure too, so the contrast between the two is explicit."""
    assert gcd(side_period(1, 0), TRAIN_PERIOD) > 1


def test_every_side_meets_every_training_phase_equally():
    """Over one full cycle, each side must see each policy-age and each CEM
    state the same number of times, or side is confounded with training phase."""
    n = 240
    s = schedule(n, 2, 1)
    train_eps = [e for e in range(n) if e % TRAIN_PERIOD == 0]
    from collections import Counter
    sides = Counter(s[e][2] for e in train_eps)
    assert sides["buy"] == sides["sell"] == sides["none"], sides
    # and the CEM on/off split must be balanced within each side.
    # NOTE on the rate: CEM is on when `episode % 8 != 0`, which is 7 of every 8
    # EPISODES -- but training only runs on multiples of 4, and among those
    # `e % 8` alternates 0, 4, 0, 4. So over TRAINING SESSIONS, which is the
    # only thing that matters, CEM is on exactly HALF the time, not 3 of 4.
    for want in ("buy", "sell"):
        on = sum(1 for e in train_eps if s[e][2] == want and bool(e % CEM_PERIOD))
        off = sum(1 for e in train_eps if s[e][2] == want and not bool(e % CEM_PERIOD))
        assert on == off, (want, on, off)


def test_cem_fires_on_half_the_training_sessions_not_three_quarters():
    """Pinning the rate because it is easy to get wrong: 7/8 of episodes satisfy
    `episode % 8 != 0`, but training only runs on multiples of 4, and among
    those the condition alternates. CLAUDE.md states the same (on at 4, 12, 20;
    off at 0, 8, 16)."""
    train_eps = [e for e in range(240) if e % TRAIN_PERIOD == 0]
    on = [e for e in train_eps if bool(e % CEM_PERIOD)]
    assert len(on) * 2 == len(train_eps), (len(on), len(train_eps))
    assert on[:3] == [4, 12, 20], on[:3]


def test_one_on_zero_off_fails_that_balance():
    n = 240
    s = schedule(n, 1, 0)
    from collections import Counter
    sides = Counter(s[e][2] for e in range(n) if e % TRAIN_PERIOD == 0)
    assert sides["sell"] == 0, "expected every training episode to be buy-side"


def test_trainer_still_uses_these_periods():
    """If either period changes, the coprimality argument must be redone."""
    import os
    src = open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..",
                            "AR_RL_Trainer.py")).read()
    assert "if ((episode) % 4 == 0):" in src, "training period is no longer 4"
    assert "bool((episode) % 8)" in src, "CEM period is no longer 8"


if __name__ == "__main__":
    mod = sys.modules[__name__]
    failures = 0
    for name in sorted(dir(mod)):
        if not name.startswith("test_"):
            continue
        try:
            getattr(mod, name)()
            print("PASS %s" % name)
        except AssertionError as e:
            failures += 1
            print("FAIL %s: %s" % (name, e))
    print("all tests passed" if not failures else "%d FAILURES" % failures)
    sys.exit(1 if failures else 0)
